### ISSUE TITLE
And error occur during installation.

### ISSUE THREAD

**Issue by khoi01** [huseinzol05/malaya#126]
Hello sir, I really interested try out your project.But i got an error during installation.I Don't know what mistake i have done. Hope can help me solve this problem.Thank you in advance.

```

(conda-env) jtm@jtms-MacBook-Pro malaya % pip install malaya
Requirement already satisfied: malaya in /Users/jtm/miniforge3/envs/conda-env/lib/python3.9/site-packages/malaya-4.9.0-py3.9.egg (4.9.0)
Collecting dateparser
  Using cached dateparser-1.1.1-py2.py3-none-any.whl (288 kB)
Collecting scikit-learn
  Using cached scikit-learn-1.1.2.tar.gz (7.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      Collecting setuptools<60.0
        Using cached setuptools-59.8.0-py3-none-any.whl (952 kB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting Cython>=0.28.5
        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.5.28-py3-none-any.whl (3.9 kB)
      Collecting scipy>=1.3.2
        Using cached scipy-1.9.0.tar.gz (42.0 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [61 lines of output]
            The Meson build system
            Version: 0.62.2
            Source dir: /private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9
            Build dir: /private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9/.mesonpy-7nzdk23l/build
            Build type: native build
            Project name: SciPy
            Project version: 1.9.0
            C compiler for the host machine: cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.3)")
            C linker for the host machine: cc ld64 711
            C++ compiler for the host machine: c++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.3)")
            C++ linker for the host machine: c++ ld64 711
            Host machine cpu family: aarch64
            Host machine cpu: arm64
            Compiler for C supports arguments -Wno-unused-but-set-variable: NO
            Library m found: YES
      
            ../../meson.build:41:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['g95']]
            The following exception(s) were encountered:
            Running "gfortran --version" gave "[Errno 2] No such file or directory: 'gfortran'"
            Running "gfortran -V" gave "[Errno 2] No such file or directory: 'gfortran'"
            Running "flang --version" gave "[Errno 2] No such file or directory: 'flang'"
            Running "flang -V" gave "[Errno 2] No such file or directory: 'flang'"
            Running "nvfortran --version" gave "[Errno 2] No such file or directory: 'nvfortran'"
            Running "nvfortran -V" gave "[Errno 2] No such file or directory: 'nvfortran'"
            Running "pgfortran --version" gave "[Errno 2] No such file or directory: 'pgfortran'"
            Running "pgfortran -V" gave "[Errno 2] No such file or directory: 'pgfortran'"
            Running "ifort --version" gave "[Errno 2] No such file or directory: 'ifort'"
            Running "ifort -V" gave "[Errno 2] No such file or directory: 'ifort'"
            Running "g95 --version" gave "[Errno 2] No such file or directory: 'g95'"
            Running "g95 -V" gave "[Errno 2] No such file or directory: 'g95'"
      
            A full log can be found at /private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9/.mesonpy-7nzdk23l/build/meson-logs/meson-log.txt
            + meson setup --native-file=/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/Users/jtm/miniforge3/envs/conda-env /private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9 /private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9/.mesonpy-7nzdk23l/build
            Traceback (most recent call last):
              File "/Users/jtm/miniforge3/envs/conda-env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
                main()
              File "/Users/jtm/miniforge3/envs/conda-env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/Users/jtm/miniforge3/envs/conda-env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
                return hook(config_settings)
              File "/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-build-env-8fd9zwcl/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 909, in get_requires_for_build_wheel
                with _project(config_settings) as project:
              File "/Users/jtm/miniforge3/envs/conda-env/lib/python3.9/contextlib.py", line 119, in __enter__
                return next(self.gen)
              File "/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-build-env-8fd9zwcl/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 888, in _project
                with Project.with_temp_working_dir(
              File "/Users/jtm/miniforge3/envs/conda-env/lib/python3.9/contextlib.py", line 119, in __enter__
                return next(self.gen)
              File "/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-build-env-8fd9zwcl/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 547, in with_temp_working_dir
                yield cls(source_dir, tmpdir, build_dir)
              File "/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-build-env-8fd9zwcl/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 463, in __init__
                self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
              File "/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-build-env-8fd9zwcl/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 494, in _configure
                self._meson(
              File "/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-build-env-8fd9zwcl/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 477, in _meson
                return self._proc('meson', *args)
              File "/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-build-env-8fd9zwcl/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 472, in _proc
                subprocess.check_call(list(args))
              File "/Users/jtm/miniforge3/envs/conda-env/lib/python3.9/subprocess.py", line 373, in check_call
                raise CalledProcessError(retcode, cmd)
            subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/Users/jtm/miniforge3/envs/conda-env', '/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9', '/private/var/folders/h0/dhcbq6457l397wg4d4rmn3l80000gn/T/pip-install-gar3w17a/scipy_8505782af44f43929c4a8900312111d9/.mesonpy-7nzdk23l/build']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


```

**Comment by khoi01** [comment]
> This depends on SciPy.
> 
> SciPy is apparently not available for your platform as a wheel, so pip tried to download the source package and compile it locally. However, compiling SciPy failed, because SciPy requires a fortran compiler and you don't have one installed.

Thanks your sir for your feedback.really appreciated and that really helped identify my problem..

Right now i refer this project malaya/requirements.txt and and it's worked. Able to install malaya from pip.
