### ISSUE TITLE
ModuleNotFoundError: youtokentome not installed. 

### ISSUE THREAD

**Issue by khoi01** [huseinzol05/malaya#127]
Hello sir,I tried to follow tutorial from this project documentation.During compiled, received an error message where i need to installed youtokentome module. But after I installed it, when I compiled again, an error occurred that I not installed the module yet, even though I had already installed the module.Hope can help me solve this problem sir.Thank you in advance.

Tutorial Documentation: https://malaya.readthedocs.io/en/stable/load-sentiment.html
Laptop: Macbook M1

ERROR MESSAGE Below When i called 'import youtokentome as yttm'

```

thon/debugpy/adapter/../../debugpy/launcher 51275 -- /Users/jtm/Documents/Learning/python/flask-example/app.py 

Traceback (most recent call last):
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/jtm/Documents/Learning/python/flask-example/app.py", line 2, in <module>
    import youtokentome as yttm
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/youtokentome/__init__.py", line 1, in <module>
    from .youtokentome import BPE
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/youtokentome/youtokentome.py", line 4, in <module>
    import _youtokentome_cython
ImportError: dlopen(/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture
        /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture
```

**ERROR MESSAGE**
```
conda-env-1) jtm@jtms-MacBook-Pro sentimen-analysis %  cd /Users/jtm/Documents/Learning/python/senti
men-analysis ; /usr/bin/env /Users/jtm/miniforge3/envs/conda-env-1/bin/python /Users/jtm/.vscode/exte
nsions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 49805
 -- /Users/jtm/Documents/Learning/python/sentimen-analysis/malaya/khoi/app.py 
Traceback (most recent call last):
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/malaya/text/bpe.py", line 141, in __init__
    import youtokentome as yttm
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/youtokentome/__init__.py", line 1, in <module>
    from .youtokentome import BPE
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/youtokentome/youtokentome.py", line 4, in <module>
    import _youtokentome_cython
ImportError: dlopen(/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture
        /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jtm/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/jtm/Documents/Learning/python/sentimen-analysis/malaya/khoi/app.py", line 14, in <module>
    model = malaya.sentiment.multinomial()
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/malaya/sentiment.py", line 89, in multinomial
    return classification.multinomial(
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/malaya/supervised/classification.py", line 96, in multinomial
    bpe = YTTMEncoder(vocab_file=path['bpe'])
  File "/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/malaya/text/bpe.py", line 143, in __init__
    raise ModuleNotFoundError(
ModuleNotFoundError: youtokentome not installed. Please install it by `pip install youtokentome` and try again.
```
**Below is the module list I installed:**
```

(conda-env-1) jtm@jtms-MacBook-Pro sentimen-analysis % pip list
Package                       Version
----------------------------- -----------
absl-py                       1.2.0
aiohttp                       3.8.1
aiosignal                     1.2.0
appnope                       0.1.3
asttokens                     2.0.5
astunparse                    1.6.3
async-timeout                 4.0.2
attrs                         22.1.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
blinker                       1.4
brotlipy                      0.7.0
cached-property               1.5.2
cachetools                    5.2.0
certifi                       2022.6.15
cffi                          1.15.1
charset-normalizer            2.1.0
click                         8.1.3
colorama                      0.4.5
cryptography                  37.0.4
cycler                        0.11.0
Cython                        0.29.32
dateparser                    1.1.0
decorator                     4.4.2
et-xmlfile                    1.0.1
executing                     0.10.0
filelock                      3.8.0
flatbuffers                   1.12
fonttools                     4.34.4
frozenlist                    1.3.1
ftfy                          6.1.1
gast                          0.4.0
google-auth                   2.10.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.46.3
h5py                          3.7.0
herpetologist                 0.0.9
huggingface-hub               0.8.1
idna                          3.3
importlib-metadata            4.11.4
ipython                       8.4.0
jedi                          0.18.1
joblib                        1.1.0
keras                         2.9.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.4
lxml                          4.9.1
malaya                        4.9.0
malaya-boilerplate            0.0.22rc0
Markdown                      3.4.1
MarkupSafe                    2.1.1
matplotlib                    3.5.3
matplotlib-inline             0.1.3
memoization                   0.4.0
multidict                     6.0.2
munkres                       1.1.4
networkx                      2.5.1
numpy                         1.23.1
oauthlib                      3.2.0
openpyxl                      3.0.9
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.4.3
parso                         0.8.3
patsy                         0.5.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.2.2
prompt-toolkit                3.0.30
protobuf                      3.20.1
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.7
pycparser                     2.21
Pygments                      2.12.0
PyJWT                         2.4.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2022.2
pytz-deprecation-shim         0.1.0.post0
pyu2f                         0.1.5
PyYAML                        6.0
regex                         2022.7.25
requests                      2.28.1
requests-oauthlib             1.3.1
rsa                           4.9
scikit-learn                  1.1.2
scipy                         1.9.0
seaborn                       0.11.2
sentencepiece                 0.1.96
setuptools                    64.0.3
six                           1.16.0
stack-data                    0.4.0
statsmodels                   0.13.2
tensorboard                   2.9.0
tensorboard-data-server       0.6.0
tensorboard-plugin-wit        1.8.1
tensorflow                    2.9.1
tensorflow-addons             0.17.1
tensorflow-estimator          2.9.0
termcolor                     1.1.0
threadpoolctl                 3.1.0
tornado                       6.2
tqdm                          4.64.0
traitlets                     5.3.0
typeguard                     2.13.3
typing_extensions             4.3.0
tzdata                        2022.1
tzlocal                       4.2
unicodedata2                  14.0.0
Unidecode                     1.3.4
urllib3                       1.26.11
wcwidth                       0.2.5
Werkzeug                      2.2.2
wheel                         0.37.1
wrapt                         1.14.1
xlrd                          2.0.1
XlsxWriter                    3.0.3
yarl                          1.7.2
youtokentome                  1.0.6
zipp                          3.8.1
```

**Comment by huseinzol05** [comment]
Module not found,

```
ModuleNotFoundError: youtokentome not installed. Please install it by `pip install youtokentome` and try again.
```

**Comment by huseinzol05** [comment]
```
ImportError: dlopen(/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture
        /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture
 ```
 
 Sure your Python is ARM?

**Comment by khoi01** [comment]
> ```
> ImportError: dlopen(/Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so, 2): no suitable image found.  Did find:
>         /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture
>         /Users/jtm/miniforge3/envs/conda-env-1/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-darwin.so: mach-o, but wrong architecture
> ```
> 
> Sure your Python is ARM?

Thank you for point the issues sir and its worked. Really appreciated your help sir.

conda create -n py-env
conda activate py-env
conda config --env --set subdir osx-64 #add this line for arm
conda install python
pip install malaya
pip install Cython  
pip install youtokentome
