### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'split'

### ISSUE THREAD

**Issue by SkylarShen** [huseinzol05/malaya#142]
Hi! I meet this error when I want to run "malaya.pos.transformer(model = 'alxlnet')":

malaya.pos.transformer(model = 'alxlnet')
Traceback (most recent call last):
  File "C:\Users\e0997980\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-44bf7811469b>", line 1, in <module>
    malaya.pos.transformer(model = 'alxlnet')
  File "C:\Users\e0997980\Anaconda3\lib\site-packages\herpetologist\__init__.py", line 100, in check
    return func(*args, **kwargs)
  File "C:\Users\e0997980\Anaconda3\lib\site-packages\malaya\pos.py", line 178, in transformer
    return tag.transformer(
  File "C:\Users\e0997980\Anaconda3\lib\site-packages\malaya\supervised\tag.py", line 59, in transformer
    tokenizer = selected_tokenizer(vocab_file=path['vocab'], spm_model_file=path['tokenizer'])
  File "C:\Users\e0997980\Anaconda3\lib\site-packages\malaya\text\bpe.py", line 90, in __init__
    v = [i.split('\t') for i in v]

AttributeError: '_io.TextIOWrapper' object has no attribute 'split'

Can you help with it? Many thanks!

**Comment by huseinzol05** [comment]
freeze ur libraries here, very weird error.
