### ISSUE TITLE
Fail to load preprocessor JSON

### ISSUE THREAD

**Issue by leowmjw** [huseinzol05/Malaya#19]
Getting  error in what seems to  be failure to find the preprocessor JSON files even though if we see the cache it seems to be there:

Output:
```
$ python mymalaya.py
Hello Malaya!!  /Users/leow/Malaya
Malaya/
├── preprocessing/
│   ├── counts_1grams.json
│   ├── counts_2grams.json
│   ├── english-malay-200k.json
│   └── version
└── version
Traceback (most recent call last):
  File "mymalaya.py", line 25, in <module>
    main()
  File "mymalaya.py", line 21, in main
    test_preprocess()
  File "mymalaya.py", line 9, in test_preprocess
    preprocessing = malaya.preprocessing.preprocessing()
  File "/Users/leow/.local/share/virtualenvs/pardocs-malaya-kqb4jXNX/lib/python3.7/sit
e-packages/malaya/preprocessing.py", line 657, in preprocessing
    speller = speller,
  File "/Users/leow/.local/share/virtualenvs/pardocs-malaya-kqb4jXNX/lib/python3.7/site-packages/malaya/preprocessing.py", line 367, in __init__
    self._segmenter = _Segmenter(maxlen_segmenter)
  File "/Users/leow/.local/share/virtualenvs/pardocs-malaya-kqb4jXNX/lib/python3.7/site-packages/malaya/preprocessing.py", line 276, in __init__
    self.bigrams = _read_stats(2)
  File "/Users/leow/.local/share/virtualenvs/pardocs-malaya-kqb4jXNX/lib/python3.7/site-packages/malaya/preprocessing.py", line 248, in _read_stats
    return json.load(fopen)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 10485761 (char 10485760)

```

Code:
```
def test_preprocess():
    string_4 = 'aahhh, malasnye nak pegi keje harini #mondayblues'
    preprocessing = malaya.preprocessing.preprocessing()
    pprint(preprocessing.process(string_4))

```

Any pointers on why it fails to load?

**Comment by huseinzol05** [comment]
Tested on 3 different clouds, all use Python 3.6, no error as in the issue. Maybe Python 3.7 json have issue with old version? Can you try run `malaya.clear_cache('preprocessing')` or manually remove `preprocessing` folder, and rerun again?

**Comment by leowmjw** [comment]
It works; thanks!
